### ISSUE TITLE
Improve the menu of tips.html page

### ISSUE THREAD

**Issue by chaidul** [skpandey885/HealhUb#44]
Hello brother, I want to work on this issue

**Comment by chaidul** [comment]
Tips.html navbar toggle not working,
I already fixed it, merge my pull request 👍

**Comment by chaidul** [comment]
- Please feedback my pull request close reason !

**Comment by skpandey885** [comment]
You only changed the brackets and few lines in your pr.
I did not assign you the issue still you created a pr.
Please create a valid issue and PR.
